version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rumbl_dev
      POSTGRES_USER: postgres


  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
